// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideotapeGalore.Repositories;

namespace VideotapeGalore.Repositories.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20181023164546_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("VideotapeGalore.Models.Entities.BorrowInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BorrowDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("FriendId");

                    b.Property<DateTime?>("ReturnDate");

                    b.Property<int>("TapeId");

                    b.HasKey("Id");

                    b.HasIndex("FriendId");

                    b.HasIndex("TapeId");

                    b.ToTable("BorrowInfos");
                });

            modelBuilder.Entity("VideotapeGalore.Models.Entities.Friend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("VideotapeGalore.Models.Entities.Review", b =>
                {
                    b.Property<int>("FriendId");

                    b.Property<int>("TapeId");

                    b.Property<int>("Rating");

                    b.HasKey("FriendId", "TapeId");

                    b.HasIndex("TapeId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("VideotapeGalore.Models.Entities.Tape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DirectorFirstName");

                    b.Property<string>("DirectorLastName");

                    b.Property<string>("Eidr");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Title");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Tapes");
                });

            modelBuilder.Entity("VideotapeGalore.Models.Entities.BorrowInfo", b =>
                {
                    b.HasOne("VideotapeGalore.Models.Entities.Friend", "Friend")
                        .WithMany("BorrowInfos")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VideotapeGalore.Models.Entities.Tape", "Tape")
                        .WithMany("BorrowInfos")
                        .HasForeignKey("TapeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VideotapeGalore.Models.Entities.Review", b =>
                {
                    b.HasOne("VideotapeGalore.Models.Entities.Friend", "Friend")
                        .WithMany("Reviews")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VideotapeGalore.Models.Entities.Tape", "Tape")
                        .WithMany("Reviews")
                        .HasForeignKey("TapeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
